# Generated by Django 2.1.7 on 2019-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptime', '0002_auto_20190224_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptimereport',
            name='docfile',
            field=models.FileField(upload_to='timereports'),
        ),
    ]
